name: Jest Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: alchemy
          POSTGRES_PASSWORD: alchemy
    steps:
      - uses: actions/checkout@v2
      - run: npm ci --dev
      - run: npx eslint .
      - run: npm test
        env:
          CI: true
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          GH_REDIRECT_URI: http://localhost:7890/api/v1/github/callback
          GH_CLIENT_ID: client_id
          GH_CLIENT_SECRET: secret
          SALT_ROUNDS: 10
          COOKIE_NAME: session
          JWT_SECRET: secret
